package com.xin.musictag.infrastructure.persistence;
import com.xin.musictag.domain.*;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.support.*; import org.springframework.stereotype.Repository;
import java.sql.*; import java.util.List;
@Repository public class JdbcBatchRepository implements BatchRepository {
 private final JdbcTemplate jdbc; public JdbcBatchRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public BatchTask create(){KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement("insert into batch_task(status,created_at,updated_at) values ('DRAFT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)",Statement.RETURN_GENERATED_KEYS);return p;},k);return require(k.getKey().longValue());}
 public BatchTask require(long id){return jdbc.query("select * from batch_task where id=?",(r,n)->new BatchTask(r.getLong("id"),r.getString("status"),r.getString("plan_json"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant()),id).stream().findFirst().orElseThrow(()->new IllegalArgumentException("Unknown batch task"));}
 public List<BatchItem> items(long task){return jdbc.query("select * from batch_item where batch_task_id=? order by id",(r,n)->row(r),task);}
 public BatchItem add(long task,Long resource,String path,String kind,String status,String basis,String lyrics,String cover,String message){KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement("insert into batch_item(batch_task_id,resource_id,relative_path,kind,status,stage,match_basis,lyrics_name,cover_name,user_message,created_at) values (?,?,?,?,?,'MATCHED',?,?,?,?,CURRENT_TIMESTAMP)",Statement.RETURN_GENERATED_KEYS);p.setLong(1,task);if(resource==null)p.setNull(2,Types.BIGINT);else p.setLong(2,resource);p.setString(3,path);p.setString(4,kind);p.setString(5,status);p.setString(6,basis);p.setString(7,lyrics);p.setString(8,cover);p.setString(9,message);return p;},k);return items(task).stream().filter(i->i.id()==k.getKey().longValue()).findFirst().orElseThrow();}
 public void plan(long id,String json){jdbc.update("update batch_task set status='CONFIRMED',plan_json=?,updated_at=CURRENT_TIMESTAMP where id=?",json,id);} public void taskStatus(long id,String status){jdbc.update("update batch_task set status=?,updated_at=CURRENT_TIMESTAMP where id=?",status,id);} public void itemStatus(long id,String status,String stage,Long version,String code,String message){jdbc.update("update batch_item set status=?,stage=?,output_version_id=?,error_code=?,user_message=? where id=?",status,stage,version,code,message,id);}
 public void recoverInterrupted(){jdbc.update("update batch_item set status='INTERRUPTED',stage='INTERRUPTED',user_message='服务重启，需重试' where status='RUNNING'");jdbc.update("update batch_task set status='INTERRUPTED',updated_at=CURRENT_TIMESTAMP where status='RUNNING'");}
 private static BatchItem row(ResultSet r)throws SQLException{return new BatchItem(r.getLong("id"),r.getLong("batch_task_id"),(Long)r.getObject("resource_id"),r.getString("relative_path"),r.getString("kind"),r.getString("status"),r.getString("stage"),r.getString("match_basis"),r.getString("lyrics_name"),r.getString("cover_name"),(Long)r.getObject("output_version_id"),r.getString("error_code"),r.getString("user_message"));}
}
